.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)null.4	6.1 (Berkeley) 1/28/88
.\"
.TH NULL 4 "January 28, 1988"
.UC 2
.SH NAME
null \- data sink
.SH SYNOPSIS
.ft B
.nf
major device number(s):
	raw: 1
minor device encoding:
	mem: 0;  kmem: 1;  null: 2
.fi
.ft R
.SH DESCRIPTION
Data written on a null special file is discarded.
.PP
Reads from a null special file always return 0 bytes.
.SH FILES
.ta \w'/dev/MAKEDEV.local  'u
/dev/null
.br
/dev/MAKEDEV	script to create special files
.br
/dev/MAKEDEV.local	script to localize special files
.DT
.SH "SEE ALSO"
mem(4)
