.TH TTT 6 
.SH NAME
ttt \- tic-tac-toe
.SH SYNOPSIS
.B /usr/games/ttt
.SH DESCRIPTION
.I Ttt
is the X and O game popular in the first grade.
This is a learning program that never makes the same
mistake twice.
.PP
Although it learns, it learns slowly.
It must lose nearly 80 games to
completely know the game.
.SH FILES
.ta 2i
/usr/games/ttt.k	learning file
