#include "defs.h"

const char BADMOD[]  = "bad modifier";
const char BADCOM[]  = "bad command";
const char BADSYM[]  = "symbol not found";
const char BADLOC[]  = "automatic variable not found";
const char NOCFN[]   = "c routine not found";
const char NOMATCH[] = "cannot locate value";
const char NOBKPT[]  = "no breakpoint set";
const char BADKET[]  = "unexpected ')'";
const char NOADR[]   = "address expected";
const char NOPCS[]   = "no process";
const char BADVAR[]  = "bad variable";
const char BADTXT[]  = "text address not found";
const char BADDAT[]  = "data address not found";
const char ODDADR[]  = "odd address";
const char EXBKPT[]  = "too many breakpoints";
const char A68BAD[]  = "bad a68 frame";
const char A68LNK[]  = "bad a68 link";
const char ADWRAP[]  = "address wrap around";
const char BADEQ[]   = "unexpected `='";
const char BADWAIT[] = "wait error: process disappeared!";
const char ENDPCS[]  = "process terminated";
const char NOFORK[]  = "try again";
const char BADSYN[]  = "syntax error";
const char NOEOR[]   = "newline expected";
const char SZBKPT[]  = "bkpt: command too long";
const char LONGFIL[] = "filename too long";
const char NOTOPEN[] = "cannot open";
const char TOODEEP[] = "$<< nesting too deep";
