/*
 * System call switch table.
 */
static const struct {
    int narg;
    const char *name;
} bsd_syscalls[] = {
	{ 0, "#0"            },     /*   0 = out-of-range */
	{ 1, "exit",         },		/*   1 = exit */
	{ 0, "fork",         },		/*   2 = fork */
	{ 3, "read",         },		/*   3 = read */
	{ 3, "write",        },		/*   4 = write */
	{ 3, "open",         },		/*   5 = open */
	{ 1, "close",        },		/*   6 = close */
	{ 4, "wait4",        },		/*   7 = wait4 */
	{ 0, "#8",           },		/*   8 = (old creat) */
	{ 2, "link",         },		/*   9 = link */
	{ 1, "unlink",       },		/*  10 = unlink */
	{ 2, "execv",        },		/*  11 = execv */
	{ 1, "chdir",        },		/*  12 = chdir */
	{ 1, "fchdir",       },		/*  13 = fchdir */
	{ 3, "mknod",        },		/*  14 = mknod */
	{ 2, "chmod",        },		/*  15 = chmod */
	{ 3, "chown",        },		/*  16 = chown; now 3 args */
	{ 2, "chflags",      },		/*  17 = chflags */
	{ 2, "fchflags",     },     /*  18 = fchflags */
	{ 4, "lseek",        },		/*  19 = lseek */
	{ 0, "getpid",       },		/*  20 = getpid */
	{ 3, "mount",        },		/*  21 = mount */
	{ 1, "umount",       },		/*  22 = umount */
	{ 6, "__sysctl",     },     /*  23 = __sysctl */
	{ 0, "getuid",       },		/*  24 = getuid */
	{ 0, "geteuid",      },		/*  25 = geteuid */
	{ 4, "ptrace",       },		/*  26 = ptrace */
	{ 0, "getppid",      },		/*  27 = getppid */
	{ 2, "statfs",       },		/*  28 = statfs */
	{ 2, "fstatfs",      },		/*  29 = fstatfs */
	{ 3, "getfsstat",    },     /*  30 = getfsstat */
	{ 4, "sigaction",    },     /*  31 = sigaction */
	{ 3, "sigprocmask",  },     /*  32 = sigprocmask */
	{ 2, "access",       },		/*  33 = access */
	{ 1, "sigpending",   },     /*  34 = sigpending */
	{ 2, "sigaltstack",  },     /*  35 = sigaltstack */
	{ 0, "sync",         },		/*  36 = sync */
	{ 2, "kill",         },		/*  37 = kill */
	{ 2, "stat",         },		/*  38 = stat */
	{ 2, "getlogin",     },		/*  39 = getlogin */
	{ 2, "lstat",        },		/*  40 = lstat */
	{ 1, "dup",          },     /*  41 = dup */
	{ 0, "pipe",         },		/*  42 = pipe */
	{ 1, "setlogin",     },		/*  43 = setlogin */
	{ 4, "profil",       },		/*  44 = profil */
	{ 1, "setuid",       },		/*  45 = setuid */
	{ 1, "seteuid",      },		/*  46 = seteuid */
	{ 0, "getgid",       },		/*  47 = getgid */
	{ 0, "getegid",      },		/*  48 = getegid */
	{ 1, "setgid",       },		/*  49 = setgid */
	{ 1, "setegid",      },		/*  50 = setegid */
	{ 0, "#51",          },		/*  51 = unused */
	{ 3, "phys",         },		/*  52 = (2.9) set phys addr */
	{ 1, "lock",         },		/*  53 = (2.9) lock in core */
	{ 4, "ioctl",        },		/*  54 = ioctl */
	{ 1, "reboot",       },		/*  55 = reboot */
	{ 2, "sigwait",      },		/*  56 = sigwait */
	{ 2, "symlink",      },		/*  57 = symlink */
	{ 3, "readlink",     },     /*  58 = readlink */
	{ 3, "execve",       },		/*  59 = execve */
	{ 1, "umask",        },		/*  60 = umask */
	{ 1, "chroot",       },		/*  61 = chroot */
	{ 2, "fstat",        },		/*  62 = fstat */
	{ 0, "#63",          },		/*  63 = reserved */
	{ 0, "#64",          },		/*  64 = (old getpagesize) */
	{ 6, "pselect",      },		/*  65 = pselect */
	{ 0, "vfork",        },		/*  66 = vfork */
	{ 0, "#67",          },		/*  67 = unused */
	{ 0, "#68",          },		/*  68 = unused */
	{ 1, "brk",          },		/*  69 = brk */
	{ 0, "#70",          },		/*  70 = unused */
	{ 0, "#71",          },		/*  71 = unused */
	{ 0, "#72",          },		/*  72 = unused */
	{ 0, "#73",          },		/*  73 = unused */
	{ 0, "#74",          },		/*  74 = unused */
	{ 0, "#75",          },		/*  75 = unused */
	{ 0, "vhangup",      },		/*  76 = vhangup */
	{ 0, "#77",          },		/*  77 = unused */
	{ 0, "#78",          },		/*  78 = unused */
	{ 2, "getgroups",    },     /*  79 = getgroups */
	{ 2, "setgroups",    },     /*  80 = setgroups */
	{ 1, "getpgrp",      },		/*  81 = getpgrp */
	{ 2, "setpgrp",      },		/*  82 = setpgrp */
	{ 3, "setitimer",    },     /*  83 = setitimer */
	{ 0, "old wait",     },		/*  84 = (old wait,wait3) */
	{ 0, "#85",          },		/*  85 = unused */
	{ 2, "getitimer",    },     /*  86 = getitimer */
	{ 0, "#87",          },		/*  87 = (old gethostname) */
	{ 0, "#88",          },		/*  88 = (old sethostname) */
	{ 0, "getdtablesize",},     /*  89 = getdtablesize */
	{ 2, "dup2",         },		/*  90 = dup2 */
	{ 0, "#91",          },		/*  91 = unused */
	{ 3, "fcntl",        },		/*  92 = fcntl */
	{ 5, "select",       },		/*  93 = select */
	{ 0, "#94",          },		/*  94 = unused */
	{ 1, "fsync",        },		/*  95 = fsync */
	{ 3, "setpriority",  },     /*  96 = setpriority */
	{ 3, "socket",       },     /*  97 = socket */
	{ 3, "connect",      },     /*  98 = connect */
	{ 3, "accept",       },     /*  99 = accept */
	{ 2, "getpriority",  },     /* 100 = getpriority */
	{ 4, "send",         },     /* 101 = send */
	{ 4, "recv",         },     /* 102 = recv */
	{ 1, "sigreturn",    },     /* 103 = sigreturn */
	{ 3, "bind",         },     /* 104 = bind */
	{ 5, "setsockopt",   },     /* 105 = setsockopt */
	{ 2, "listen",       },     /* 106 = listen */
	{ 1, "sigsuspend",   },     /* 107 = sigsuspend */
	{ 0, "#108",         },		/* 108 = (old sigvec) */
	{ 0, "#109",         },		/* 109 = (old sigblock) */
	{ 0, "#110",         },		/* 110 = (old sigsetmask) */
	{ 0, "#111",         },		/* 111 = (old sigpause)  */
	{ 2, "sigstack",     },     /* 112 = sigstack COMPAT-43 */
	{ 3, "recvmsg",      },     /* 113 = recvmsg */
	{ 3, "sendmsg",      },     /* 114 = sendmsg */
	{ 0, "#115",         },		/* 115 = unused */
	{ 2, "gettimeofday", },     /* 116 = gettimeofday */
	{ 2, "getrusage",    },     /* 117 = getrusage */
	{ 5, "getsockopt",   },     /* 118 = getsockopt */
	{ 0, "#119",         },		/* 119 = unused */
	{ 3, "readv",        },		/* 120 = readv */
	{ 3, "writev",       },		/* 121 = writev */
	{ 2, "settimeofday", },     /* 122 = settimeofday */
	{ 3, "fchown",       },		/* 123 = fchown */
	{ 2, "fchmod",       },		/* 124 = fchmod */
	{ 6, "recvfrom",     },     /* 125 = recvfrom */
	{ 0, "#126",         },		/* 126 = (old setreuid) */
	{ 0, "#127",         },		/* 127 = (old setregid) */
	{ 2, "rename",       },		/* 128 = rename */
	{ 3, "truncate",     },     /* 129 = truncate */
	{ 3, "ftruncate",    },     /* 130 = ftruncate */
	{ 2, "flock",        },		/* 131 = flock */
	{ 0, "#132",         },		/* 132 = nosys */
	{ 6, "sendto",       },     /* 133 = sendto */
	{ 2, "shutdown",     },     /* 134 = shutdown */
	{ 4, "socketpair",   },     /* 135 = socketpair */
	{ 2, "mkdir",        },		/* 136 = mkdir */
	{ 1, "rmdir",        },		/* 137 = rmdir */
	{ 2, "utimes",       },		/* 138 = utimes */
	{ 0, "#139",         },		/* 139 = unused */
	{ 2, "adjtime",      },		/* 140 = adjtime */
	{ 3, "getpeername",  },     /* 141 = getpeername */
	{ 0, "#142",         },		/* 142 = (old gethostid) */
	{ 0, "#143",         },		/* 143 = (old sethostid) */
	{ 2, "getrlimit",    },     /* 144 = getrlimit */
	{ 2, "setrlimit",    },     /* 145 = setrlimit */
	{ 2, "killpg",       },		/* 146 = killpg */
	{ 0, "#147",         },		/* 147 = nosys */
	{ 2, "setquota",     },		/* 148 = quota */
	{ 4, "quota",        },		/* 149 = qquota */
	{ 3, "getsockname",  },     /* 150 = getsockname */
	{ 0, "#151",         },		/* 151 = unused */
	{ 0, "nostk",        },		/* 152 = nostk */
	{ 1, "fetchi",       },		/* 153 = fetchi */
	{ 4, "ucall",        },		/* 154 = ucall */
	{ 0, "fperr",        },		/* 155 = fperr */
};
