.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)sigpause.2	6.2.1 (2.11BSD) 97/9/2
.\"
.TH SIGPAUSE 2 "September 2, 1997"
.UC 4
.SH NAME
sigpause \- atomically release blocked signals and wait for interrupt
.SH SYNOPSIS
\fBsigpause\fP(\fIsigmask\fP)
.br
long \fIsigmask\fP;
.SH DESCRIPTION
.B This interface is made obsolete by:
sigsuspend(2).
.PP
.B Sigpause()
assigns 
.I sigmask
to the set of masked signals
and then waits for a signal to arrive;
on return the set of masked signals is restored.
.I Sigmask
is usually 0L to indicate that no
signals are now to be blocked.
.B Sigpause
always terminates by being interrupted, returning \-1 with
.I errno
set to EINTR.
.SH SEE ALSO
sigsuspend(2), kill(2), sigaction(2), sigprocmask(2), sigblock(2),
sigvec(2)
.SH HISTORY
The
.B sigpause
function call appeared in 4.2BSD and has been deprecated.
