/* name (COLOR)			owner	type	desc		cost	*/

{"=== GO ===",			-1,	SAFE,	0                               },
{"Mediterranean ave. (P)",	-1,	PRPTY,	(char*)&prop[0],	60	},
{"Community Chest i",		-1,	CC,	(char*)cc			},
{"Baltic ave. (P)",		-1,	PRPTY,	(char*)&prop[1],	60	},
{"Income Tax",			-1,	SPEC,	(char*)inc_tax			},
{"Reading RR",			-1,	RR,	(char*)&rr[0],		200	},
{"Oriental ave. (L)",		-1,	PRPTY,	(char*)&prop[2],	100	},
{"Chance i",			-1,	CHANCE,	(char*)chance			},
{"Vermont ave. (L)",		-1,	PRPTY,	(char*)&prop[3],	100	},
{"Connecticut ave. (L)",	-1,	PRPTY,	(char*)&prop[4],	120	},
{"Just Visiting",		-1,	SAFE,	0			},
{"St. Charles pl. (V)",		-1,	PRPTY,	(char*)&prop[5],	140	},
{"Electric Co.",		-1,	UTIL,	(char*)&util[0],	150	},
{"States ave. (V)",		-1,	PRPTY,	(char*)&prop[6],	140	},
{"Virginia ave. (V)",		-1,	PRPTY,	(char*)&prop[7],	160	},
{"Pennsylvania RR",		-1,	RR,	(char*)&rr[1],		200	},
{"St. James pl. (O)",		-1,	PRPTY,	(char*)&prop[8],	180	},
{"Community Chest ii",		-1,	CC,	(char*)cc			},
{"Tennessee ave. (O)",		-1,	PRPTY,	(char*)&prop[9],	180	},
{"New York ave. (O)",		-1,	PRPTY,	(char*)&prop[10],	200	},
{"Free Parking",		-1,	SAFE,	0                               },
{"Kentucky ave. (R)",		-1,	PRPTY,	(char*)&prop[11],	220	},
{"Chance ii",			-1,	CHANCE,	(char*)chance			},
{"Indiana ave. (R)",		-1,	PRPTY,	(char*)&prop[12],	220	},
{"Illinois ave. (R)",		-1,	PRPTY,	(char*)&prop[13],	240	},
{"B&O RR",			-1,	RR,	(char*)&rr[2],		200	},
{"Atlantic ave. (Y)",		-1,	PRPTY,	(char*)&prop[14],	260	},
{"Ventnor ave. (Y)",		-1,	PRPTY,	(char*)&prop[15],	260	},
{"Water Works",			-1,	UTIL,	(char*)&util[1],	150	},
{"Marvin Gardens (Y)",		-1,	PRPTY,	(char*)&prop[16],	280	},
{"GO TO JAIL",			-1,	SPEC,	(char*)goto_jail		},
{"Pacific ave. (G)",		-1,	PRPTY,	(char*)&prop[17],	300	},
{"N. Carolina ave. (G)",	-1,	PRPTY,	(char*)&prop[18],	300	},
{"Community Chest iii",		-1,	CC,	(char*)cc			},
{"Pennsylvania ave. (G)",	-1,	PRPTY,	(char*)&prop[19],	320	},
{"Short Line RR",		-1,	RR,	(char*)&rr[3],		200	},
{"Chance iii",			-1,	CHANCE,	(char*)chance			},
{"Park place (D)",		-1,	PRPTY,	(char*)&prop[20],	350	},
{"Luxury Tax",			-1,	SPEC,	(char*)lux_tax			},
{"Boardwalk (D)",		-1,	PRPTY,	(char*)&prop[21],	400	},
{"JAIL",			-1,	SPEC                                    }
